config/routes.rb
Rails.application.routes.draw do
	  
  
  
  resources :idiomas
  resources :capacidads
  resources :nivelacademicos
  resources :titulos
  resources :carreras
  resources :personas
	resources :empresas do
        resources :perfilempresas
  end
	resources :postulantes do
	  		resources :exp_laborals
	  		resources :estudios
	  end
	  devise_for :users
  	  root 'welcome#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/capacidad.rb
class Capacidad < ApplicationRecord
end

app/models/carrera.rb
class Carrera < ApplicationRecord
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	validates :ruc, presence: true, numericality: true, uniqueness: true #validacion para que el ruc no se repita
	validates :nombre, presence: true
	validates :direccion, presence: true
	validates :telefono, presence: true, numericality: true
	validates :email, presence: true


	has_many :exp_laborals
	has_many :perfilempresas
end

app/models/estudio.rb
class Estudio < ApplicationRecord
  belongs_to :user
  belongs_to :postulante
end

app/models/exp_laboral.rb
class ExpLaboral < ApplicationRecord
	belongs_to :user
	belongs_to :postulante
	belongs_to :empresa, optional: true
end

app/models/idioma.rb
class Idioma < ApplicationRecord
end

app/models/nivelacademico.rb
class Nivelacademico < ApplicationRecord
end

app/models/perfilempresa.rb
class Perfilempresa < ApplicationRecord
	belongs_to :user
	belongs_to :empresa
end

app/models/persona.rb
class Persona < ApplicationRecord

	validates :nombre, presence: true 
	validates :apellido, presence: true
	validates :cedula, presence: true, numericality: true, uniqueness: true #validacion para que el ruc no se repita
	validates :correo, presence: true
	
end

app/models/postulante.rb
class Postulante < ApplicationRecord
	validates :cedula, presence: true, uniqueness: true
	validates :nombres, presence: true
	validates :fecha_nacimiento, presence: true
	validates :edad, presence: true
	validates :sexo, presence: true
	validates :nacionalidad, presence: true
	validates :estado_civil, presence: true
	validates :telefono, presence: true
	validates :direccion, presence: true, length: {minimum: 10}
	validates :mas_info, presence: true
	validates :idioma, presence: true

	has_many :estudios
	has_many :exp_laborals
	belongs_to :user, optional: true
end

app/models/titulo.rb
class Titulo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :postulantes
    has_many :estudios
    has_many :personas
    has_many :exp_laborals
	has_many :perfilempresas	
	has_many :empresas
	has_many :perfilempresas

end

app/controllers/capacidads_controller.rb
class CapacidadsController < ApplicationController
  before_action :set_capacidad, only: [:show, :edit, :update, :destroy]

  # GET /capacidads
  # GET /capacidads.json
  def index
    @capacidads = Capacidad.all
  end

  # GET /capacidads/1
  # GET /capacidads/1.json
  def show
  end

  # GET /capacidads/new
  def new
    @capacidad = Capacidad.new
  end

  # GET /capacidads/1/edit
  def edit
  end

  # POST /capacidads
  # POST /capacidads.json
  def create
    @capacidad = Capacidad.new(capacidad_params)

    respond_to do |format|
      if @capacidad.save
        format.html { redirect_to @capacidad, notice: 'Capacidad was successfully created.' }
        format.json { render :show, status: :created, location: @capacidad }
      else
        format.html { render :new }
        format.json { render json: @capacidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capacidads/1
  # PATCH/PUT /capacidads/1.json
  def update
    respond_to do |format|
      if @capacidad.update(capacidad_params)
        format.html { redirect_to @capacidad, notice: 'Capacidad was successfully updated.' }
        format.json { render :show, status: :ok, location: @capacidad }
      else
        format.html { render :edit }
        format.json { render json: @capacidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capacidads/1
  # DELETE /capacidads/1.json
  def destroy
    @capacidad.destroy
    respond_to do |format|
      format.html { redirect_to capacidads_url, notice: 'Capacidad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capacidad
      @capacidad = Capacidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capacidad_params
      params.require(:capacidad).permit(:tipo, :nivel)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/capacidads_helper.rb
module CapacidadsHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/postulante_helper.rb
module PostulanteHelper
end

app/helpers/titulos_helper.rb
module TitulosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/capacidads/_form.html.erb
<%= form_with(model: capacidad, local: true) do |form| %>
  <% if capacidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(capacidad.errors.count, "error") %> prohibited this capacidad from being saved:</h2>

      <ul>
      <% capacidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :nivel %>
    <%= form.text_field :nivel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/capacidads/edit.html.erb
<h1>Editing Capacidad</h1>

<%= render 'form', capacidad: @capacidad %>

<%= link_to 'Show', @capacidad %> |
<%= link_to 'Back', capacidads_path %>

app/views/capacidads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Capacidads</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Nivel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @capacidads.each do |capacidad| %>
      <tr>
        <td><%= capacidad.tipo %></td>
        <td><%= capacidad.nivel %></td>
        <td><%= link_to 'Show', capacidad %></td>
        <td><%= link_to 'Edit', edit_capacidad_path(capacidad) %></td>
        <td><%= link_to 'Destroy', capacidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capacidad', new_capacidad_path %>

app/views/capacidads/new.html.erb
<h1>New Capacidad</h1>

<%= render 'form', capacidad: @capacidad %>

<%= link_to 'Back', capacidads_path %>

app/views/capacidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @capacidad.tipo %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @capacidad.nivel %>
</p>

<%= link_to 'Edit', edit_capacidad_path(@capacidad) %> |
<%= link_to 'Back', capacidads_path %>